### ISSUE TITLE
Working good with Redmine4.1 if RMagick is added

### ISSUE THREAD

**Issue by n0nel** [suer/redmine_issues_summary_graph#12]
Redmine version 4.1 has switched from RMagick to MiniMagick.
To work this plugin, RMagic must be installed separately.

Add "**redmine_issues_summary_graph/Gemfile**" file.

```
source 'https://rubygems.org'

platforms :mri, :mingw, :x64_mingw do
  # Optional gem for exporting the gantt to a PNG file, not supported with jruby
  group :rmagick do
    gem "rmagick", "~> 2.16.0"
  end
end
```
Modify "**redmine_issues_summary_graph/init.rb**" file.

```
--- org/redmine_issues_summary_graph/init.rb
+++ new/redmine_issues_summary_graph/init.rb
@@ -1,3 +1,4 @@
 require 'redmine'
+require 'rmagick'
 
 Redmine::Plugin.register :redmine_issues_summary_graph do
```

And install this plugin.

```
bundle install
bundle exec rake redmine:plugins:migrate
```

> In Japanese:
> シンプルなプラグインで、以前から利用しています。
> とりあえず、RMagicで動かすように手直ししました。
> ぜひMiniMagick対応をしていただけるようよろしくお願いします。

**Comment by n0nel** [comment]
Thank you for quick MiniMagick support.
This version will succeed on some attempts, but in most cases,

"**Errno :: E2BIG (Arg list too long-convert):**" occurs.

It seems the count of function "gc.draw()" calling is relevant?

The following is the result in production.log.
In the "app/helpers/issues_summary_graph_helper.rb",
in the "draw_line()" function,
"`(prev_x.floor + 1) .upto (x.floor) do | tmp_x |`"
block commented out, and executed it.

Success log:
In this case summary period is from **2019-09-28** to 2020-01-20.
```
Started POST "/redmine/issues_summary_graph/some_project/show" for 127.0.0.1 at 2020-01-20
Processing by IssuesSummaryGraphController#show as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "closed_status_ids"=>["5", ...], "tracker_ids"=>["1", ...], "from"=>"2019-09-28", "to"=>"2020-01-20", "version_ids"=>["0", ...], "commit"=>"Reload", "project_id"=>"some_project"}
  Current user: admin (id=1)
  Rendering plugins/redmine_issues_summary_graph/app/views/issues_summary_graph/show.html.erb within layouts/base
  Rendered plugins/redmine_issues_summary_graph/app/views/issues_summary_graph/show.html.erb within layouts/base (5.2ms)
Completed 200 OK in 70ms (Views: 37.4ms | ActiveRecord: 22.3ms)
Started GET "/redmine/issues_summary_graph/some_project/summary_graph.png?closed_issue_statuses%5B%5D=5&...&from=2019-09-28&include_subproject=false&to=2020-01-20&tracker_ids%5B%5D=1&...&versions%5B%5D=0&..." for 127.0.0.1 at 2020-01-20
Processing by IssuesSummaryGraphController#summary_graph as PNG
  Parameters: {"closed_issue_statuses"=>["5", ...], "from"=>"2019-09-28", "include_subproject"=>"false", "to"=>"2020-01-20", "tracker_ids"=>["1", ...], "versions"=>["0", ...], "project_id"=>"some_project"}
  Current user: admin (id=1)
  Rendering text template
  Rendered text template (0.0ms)
Sent data summary.png (0.5ms)
Completed 200 OK in 1007ms (Views: 0.4ms | ActiveRecord: 110.4ms)
```

Failure log:
In this case summary period is from **2019-09-27** to 2020-01-20.
```
Started POST "/redmine/issues_summary_graph/some_project/show" for 127.0.0.1 at 2020-01-20
Processing by IssuesSummaryGraphController#show as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "closed_status_ids"=>["5", ...], "tracker_ids"=>["1", ...], "from"=>"2019-09-27", "to"=>"2020-01-20", "version_ids"=>["0", ...], "commit"=>"Reload", "project_id"=>"some_project"}
  Current user: admin (id=1)
  Rendering plugins/redmine_issues_summary_graph/app/views/issues_summary_graph/show.html.erb within layouts/base
  Rendered plugins/redmine_issues_summary_graph/app/views/issues_summary_graph/show.html.erb within layouts/base (4.4ms)
Completed 200 OK in 67ms (Views: 40.2ms | ActiveRecord: 19.4ms)
Started GET "/redmine/issues_summary_graph/some_project/summary_graph.png?closed_issue_statuses%5B%5D=5&...&from=2019-09-27&include_subproject=false&to=2020-01-20&tracker_ids%5B%5D=1&...&versions%5B%5D=0&..." for 127.0.0.1 at 2020-01-20
Processing by IssuesSummaryGraphController#summary_graph as PNG
  Parameters: {"closed_issue_statuses"=>["5", ...], "from"=>"2019-09-27", "include_subproject"=>"false", "to"=>"2020-01-20", "tracker_ids"=>["1", ...], "versions"=>["0", ...], "project_id"=>"some_project"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 286ms (ActiveRecord: 96.1ms)
  
Errno::E2BIG (Arg list too long - convert):
  
plugins/redmine_issues_summary_graph/app/helpers/issues_summary_graph_helper.rb:80:in `draw_summary_graph'
plugins/redmine_issues_summary_graph/app/helpers/issues_summary_graph_helper.rb:61:in `generate_summary_graph'
plugins/redmine_issues_summary_graph/app/controllers/issues_summary_graph_controller.rb:43:in `summary_graph'
```

**Comment by n0nel** [comment]
I understood this problem was caused by a specific environment (windows).
I will continue to investigate the way to split the 'Convert' command.

**Comment by suer** [comment]
Thank you for testing!

I added a commit https://github.com/suer/redmine_issues_summary_graph/pull/13/commits/72d98339959f3ec95caf2fb29cea1a25c134d418 to reduce command length using polyline and polygon.
On mac, I have confirmed that it works well with several years data.


Current version of this plugin summarize issues by day.
So the command length grows in proportion to the number of days in the period.
There is way to split convert commands, but it may be splitted to too many sub commands. 
As a result, they will increase machine load.

In order to handle more time periods,  it is necessary to summarize by week or month.

**Comment by n0nel** [comment]
> I added a commit [72d9833](https://github.com/suer/redmine_issues_summary_graph/commit/72d98339959f3ec95caf2fb29cea1a25c134d418) to reduce command length using polyline and polygon.
> On mac, I have confirmed that it works well with several years data.

Thank you for improvement.
The time period has expanded to about 450 days.
However, the current version using RMagick is able to display for more than 5 years.
Well, I have to consider how to respond.

**Comment by suer** [comment]
I improved it further.

`convert` command will be about 20,000 bytes when I execute current version to specify term as 10 years.
(Yesterday's version generated 220,000 bytes)

I don't know how much bytes can commands run on Windows.
Maybe 8192 bytes, so we need to reduce it more.

I got command size in the following way:

```diff
--- a/app/helpers/issues_summary_graph_helper.rb
+++ b/app/helpers/issues_summary_graph_helper.rb
@@ -91,6 +91,8 @@ module IssuesSummaryGraphHelper
       gc.stroke(COLOR_ALL).strokewidth(3).fill(COLOR_ALL).draw('line %g,%g %g,%g' % [PADDING + 10, 20, PADDING + 40, 20])
       gc.stroke(COLOR_CLOSED).strokewidth(3).fill(COLOR_CLOSED).draw('line %g,%g %g,%g' % [PADDING + 10, 40, PADDING + 40, 40])
       gc << img.path
+
+      open('convert_command.txt', 'w') { |f| f.puts  gc.command }
     end

     img.to_blob
```

**Comment by n0nel** [comment]
Wow, using the latest version, the graph displayed more than five years!
I don't know why, but the command line characters number was over 8192, reaching 15,000 on Windows.
I will continue to investigate.

**Comment by n0nel** [comment]
On Windows, max command line character number was about 32000.
To handle that finite max, I wrote a simple exception code.
```
--- org/app/helpers/issues_summary_graph_helper.rb
+++ new/app/helpers/issues_summary_graph_helper.rb
@@ -95,4 +95,16 @@
 
     img.to_blob
+  rescue
+    MiniMagick::Tool::Convert.new do |gc|
+      gc.size('%dx%d' % [SUMMARY_IMAGE_WIDTH, SUMMARY_IMAGE_HEIGHT])
+      gc.xc('white')
+      gc.stroke('transparent').fill('red')
+      font_path = Redmine::Configuration['minimagick_font_path'].presence
+      gc.font(font_path) if font_path.present?
+      gc.draw('text %d,%d %s' % [PADDING + 45, 25, Redmine::Utils::Shell.shell_quote(l(:graph_error_message1))])
+      gc.draw('text %d,%d %s' % [PADDING + 45, 45, Redmine::Utils::Shell.shell_quote(l(:graph_error_message2))])
+      gc << img.path
+    end
+    img.to_blob
   ensure
     img.destroy! if img

--- org/config/locales/en.yml
+++ new/config/locales/en.yml
@@ -7,2 +7,4 @@
   reload: Reload
   include_subproject: Include Subproject
+  graph_error_message1: Too many data.
+  graph_error_message2: Please reduce the time period.

--- org/config/locales/ja.yml
+++ new/config/locales/ja.yml
@@ -6,2 +6,4 @@
   reload: 更新
   include_subproject: サブプロジェクトを含む
+  graph_error_message1: データが多すぎます.
+  graph_error_message2: 期間を短くしてください.
```

**Comment by suer** [comment]
It's a simple solution.
It looks good for me!

I created a commit based on your idea and patch.
I will check operations, then merge it.
